/*
* Apply in https://bottlecaps.de/rr/ui
*/
Query ::= ( (Sentence+) | '|' )*

Sentence ::= ('.' key?) | ('[' index ']') | ('(' booleanQuery ')')

booleanQuery ::= (key unaryOp) | (key binaryOp literal) | (key)

unaryOp ::= 'not' | 'notEmpty' | 'empty'

binaryOp ::= 'eq' | 'gt' | 'gte' | 'lt' | 'lte'

index ::= [0-9]*

key ::= [a-zA-Z][a-zA-Z0-9]*

literal ::= '"' [*] '"'
