name: ci
on:
  pull_request:
  push:
    branches: [ 'main' ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup HLint
        uses: haskell/actions/hlint-setup@v1
        with:
          version: '3.1.6'
      - name: HLint
        uses: haskell/actions/hlint-run@v1
        with:
          path: '["src/","app/","test/"]'
          fail-on: warning
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Stack cache
        uses: actions/cache@v1
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-ci-${{ env.cache-name }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-ci-${{ env.cache-name }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('stack.yaml') }}-
            ${{ runner.os }}-ci-${{ env.cache-name }}-${{ hashFiles('package.yaml') }}-
            ${{ runner.os }}-ci-${{ env.cache-name }}-
            ${{ runner.os }}-ci-
            ${{ runner.os }}-
      - name: build
        run: make build
      - name: test
        run: make test